[tool.poetry]
name = "ddrsongaggregator"
version = "0.1.0"
description = ""
authors = ["MSoup <charmanduh@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
scrapy = "^1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
